title: channy's page 
description: Welcome! This is Qianni Huang(qanny, or you can call me channy), a software engineer mainly in Computer Vision, expecially in 3D reconstruction. But this area is too hard to find a job in my city, so I decide to change my area to Linux network coding. This blog is used to write some notes I learned in CV or others.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
markdown: kramdown